name: Terraform EC2 Deploy

on:
  push:
    branches:
      - main

jobs:

  # 🔹 Stage 0 - Clone
  clone:
    name: 🔹 Stage 0 - Clone
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Upload Source
      uses: actions/upload-artifact@v4
      with:
        name: source
        path: .


  # 🔹 Stage 1 - Init
  terraform-init:
    name: 🔹 Stage 1 - Terraform Init
    runs-on: ubuntu-latest
    needs: clone

    env:
      AWS_REGION: ap-south-1

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: source

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: hashicorp/setup-terraform@v3

    - run: terraform init
      run: terraform init

    - name: Upload Init
      uses: actions/upload-artifact@v4
      with:
        name: tf-init
        path: .


  # 🔹 Stage 2 - Validate
  terraform-validate:
    name: 🔹 Stage 2 - Terraform Validate
    runs-on: ubuntu-latest
    needs: terraform-init

    env:
      AWS_REGION: ap-south-1

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: tf-init

    - uses: hashicorp/setup-terraform@v3

    - run: terraform validate

    - name: Upload Validate
      uses: actions/upload-artifact@v4
      with:
        name: tf-validate
        path: .


  # 🔹 Stage 3 - Plan
  terraform-plan:
    name: 🔹 Stage 3 - Terraform Plan
    runs-on: ubuntu-latest
    needs: terraform-validate

    env:
      AWS_REGION: ap-south-1

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: tf-validate

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: hashicorp/setup-terraform@v3

    - run: terraform plan -out=tfplan

    - name: Upload Plan
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: tfplan


  # 🔹 Stage 4 - Apply
  terraform-apply:
    name: 🔹 Stage 4 - Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform-plan

    env:
      AWS_REGION: ap-south-1

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: source

    - uses: actions/download-artifact@v4
      with:
        name: tfplan

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - uses: hashicorp/setup-terraform@v3

    - run: terraform init
     run: terraform init

    - run: terraform apply -auto-approve tfplan